### ISSUE TITLE
Facebook Icon not appearing

### ISSUE THREAD

**Issue by kpiyush04** [commudle/commudle#55]
While updating my Facebook icon was not working I have attached the screenshot for the reference.

![Screenshot from 2020-08-23 23-42-29](https://user-images.githubusercontent.com/44132300/90985550-67f42800-e59a-11ea-84a3-415fbea84ca2.png)

**Comment by arpansac** [comment]
Oops, this repository is closed :P

Please raise an issue here: [Commude](https://github.com/commudle/commudle-ng)
